import type {
  GlossaryItem,
  PlaygroundSection,
  PrincipleCard,
} from '@/components/dev/design-system/types'

export const COVERAGE_DOCUMENTED_NOW: string[] = [
  'Foundations: surface, text, border, accent, focus ring, radius, fonts',
  'Shared UI: buttons, inputs, menus, overlays, tabs',
  'Volleyball: player token and player actions panel',
  'Principles with do/don\'t examples and concrete numeric guidance',
  'Per-section copy payloads for agent handoff',
]

export const COVERAGE_COMING_NEXT: string[] = [
  'Sidebar and navigation variants',
  'Charts, stats panels, and game-time-specific shells',
  'Print-specific presentation rules',
  'Animation token set expansion and motion audit references',
  'Role color accessibility snapshots for each theme mode',
]

export const PRINCIPLE_CARDS: PrincipleCard[] = [
  {
    id: 'color',
    title: 'Color',
    rule: 'Use semantic colors (surface, text, border, accent) before one-off colors.',
    why: 'Coaches should learn patterns once. Semantic color rules keep the interface predictable across whiteboard, teams, and game views.',
    doExample: 'Use surface + border tokens for cards, then accent only for key actions.',
    dontExample: 'Pick a new random color for each screen section or interaction state.',
    numericGuideline: 'Keep body text contrast at or above 4.5:1; reserve accent for high-priority actions and focus cues.',
    usage: [
      {
        id: 'color-settings',
        text: 'Accent and semantic colors appear in the Settings screen actions and toggles.',
        href: '/settings',
        openLabel: 'Open settings example',
      },
      {
        id: 'color-whiteboard',
        text: 'Whiteboard controls use surface and border tokens to stay readable over court visuals.',
        href: '/',
        openLabel: 'Open whiteboard example',
      },
    ],
  },
  {
    id: 'typography',
    title: 'Typography',
    rule: 'Use one body family and one display family with consistent hierarchy.',
    why: 'Coaches scan quickly during practice. Predictable type scale and weight improve readability under pressure.',
    doExample: 'Body text stays in the base family; section headings use the display family and tighter tracking.',
    dontExample: 'Mix many unrelated fonts or rely on weight-only hierarchy without size structure.',
    numericGuideline: 'Body copy targets 14-16px; section titles 18-24px; maintain line-height around 1.4-1.6 for dense screens.',
    usage: [
      {
        id: 'type-teams',
        text: 'Team cards use consistent heading and supporting text hierarchy.',
        href: '/teams',
        openLabel: 'Open teams typography',
      },
      {
        id: 'type-learn',
        text: 'Learning panels rely on body/display separation for scannable instructions.',
        href: '/learn',
        openLabel: 'Open learning typography',
      },
    ],
  },
  {
    id: 'spacing',
    title: 'Spacing',
    rule: 'Use fixed spacing steps so related controls feel grouped and rhythm stays consistent.',
    why: 'Stable spacing helps users predict where controls and details live, reducing hunting and accidental taps.',
    doExample: 'Use repeatable vertical spacing between section title, helper text, controls, and actions.',
    dontExample: 'Pack one section tightly and another loosely without a shared pattern.',
    numericGuideline: 'Use an 8px rhythm for layout spacing; keep interactive control groups at 8-12px gaps.',
    usage: [
      {
        id: 'spacing-roster',
        text: 'Roster editing uses predictable spacing steps for add/edit/remove flows.',
        href: '/roster',
        openLabel: 'Open roster spacing example',
      },
      {
        id: 'spacing-gametime',
        text: 'Game setup uses repeated section spacing to keep checklists readable.',
        href: '/gametime',
        openLabel: 'Open game setup spacing',
      },
    ],
  },
  {
    id: 'roundness',
    title: 'Corner Roundness',
    rule: 'Roundness communicates permanence and priority. Use a small set of radius tiers.',
    why: 'Consistent roundness makes interface pieces feel related and helps users distinguish temporary overlays from regular controls.',
    doExample: 'Inputs/buttons use medium radius; dialogs/sheets use larger radius for temporary context shifts.',
    dontExample: 'Use different corner values everywhere, or mix very sharp and very soft corners in one control group.',
    numericGuideline: 'Use 8px for compact controls, 10-12px for standard controls, and 14-16px for overlays.',
    usage: [
      {
        id: 'roundness-teams-dialog',
        text: 'Team creation and import overlays use larger roundness than inline controls.',
        href: '/teams',
        openLabel: 'Open team dialog example',
      },
      {
        id: 'roundness-whiteboard-controls',
        text: 'Whiteboard header controls keep medium roundness for quick taps.',
        href: '/',
        openLabel: 'Open whiteboard controls',
      },
    ],
  },
  {
    id: 'states',
    title: 'Interaction States',
    rule: 'Every interactive piece must clearly show default, hover/focus, pressed, and disabled states.',
    why: 'Coaches need confident feedback while moving quickly. State clarity reduces misclicks and missed actions.',
    doExample: 'Pressed states darken and focus rings are clearly visible against nearby surfaces.',
    dontExample: 'Only change opacity slightly or rely on color shifts that are hard to notice.',
    numericGuideline: 'Touch targets should be at least 44px in either width or height; focus indicators should be visibly distinct from borders.',
    usage: [
      {
        id: 'states-settings',
        text: 'Settings toggles and action buttons show strong focus and disabled affordances.',
        href: '/settings',
        openLabel: 'Open settings states',
      },
      {
        id: 'states-court-context',
        text: 'Player action controls provide clear selected/unselected states during planning.',
        href: '/',
        openLabel: 'Open player action states',
      },
    ],
  },
]

export const GLOSSARY_ITEMS: GlossaryItem[] = [
  {
    id: 'foundation-surface',
    name: 'Surface Colors',
    category: 'Foundation',
    purpose: 'Defines background layers so content hierarchy is clear in both light and dark themes.',
    defaults: [
      'Base background: var(--c-bg)',
      'Cards and popovers: var(--c-surface)',
      'Borders: var(--c-border)',
    ],
    usage: [
      {
        id: 'surface-whiteboard',
        text: 'Court controls and side panels use these surface layers to stay readable over graphics.',
        href: '/',
        openLabel: 'Open whiteboard surfaces',
      },
      {
        id: 'surface-teams',
        text: 'Team cards and dialogs rely on card and popover surfaces for hierarchy.',
        href: '/teams',
        openLabel: 'Open teams surfaces',
      },
    ],
  },
  {
    id: 'foundation-accent',
    name: 'Accent + Focus Ring',
    category: 'Foundation',
    purpose: 'Highlights primary actions and keyboard focus so intent and navigation are obvious.',
    defaults: [
      'Primary accent: var(--c-accent)',
      'Primary action color: var(--primary)',
      'Focus ring color: var(--ring)',
    ],
    usage: [
      {
        id: 'accent-settings',
        text: 'Primary settings actions and toggles use accent and ring tokens.',
        href: '/settings',
        openLabel: 'Open settings accent usage',
      },
      {
        id: 'accent-roster',
        text: 'Roster actions use the same accent logic for consistency with teams and whiteboard.',
        href: '/roster',
        openLabel: 'Open roster accent usage',
      },
    ],
  },
  {
    id: 'foundation-radius',
    name: 'Radius Scale',
    category: 'Foundation',
    purpose: 'Controls visual softness and communicates whether an element is regular UI or temporary overlay.',
    defaults: [
      'Base radius token: var(--radius)',
      'Standard controls: rounded-md / rounded-lg',
      'Overlays: rounded-lg / rounded-xl',
    ],
    usage: [
      {
        id: 'radius-teams',
        text: 'Team creation dialogs use larger roundness than inline form inputs.',
        href: '/teams',
        openLabel: 'Open radius usage in teams',
      },
      {
        id: 'radius-whiteboard',
        text: 'Header controls on the whiteboard use medium corners for quick scanning.',
        href: '/',
        openLabel: 'Open radius usage on whiteboard',
      },
    ],
  },
  {
    id: 'foundation-fonts',
    name: 'Font Roles',
    category: 'Foundation',
    purpose: 'Separates long-form readability from condensed headline emphasis.',
    defaults: [
      'Body: var(--font-sans)',
      'Headings: var(--font-display)',
      'Heading tracking: var(--tracking-tight)',
    ],
    usage: [
      {
        id: 'font-learn',
        text: 'Learning pages use body text for explanations and display text for sections.',
        href: '/learn',
        openLabel: 'Open font usage in learn',
      },
      {
        id: 'font-settings',
        text: 'Settings headers and control labels follow the same hierarchy pattern.',
        href: '/settings',
        openLabel: 'Open font usage in settings',
      },
    ],
  },
  {
    id: 'shared-button',
    name: 'Button',
    category: 'Shared UI',
    purpose: 'Primary and secondary action trigger with predictable hover, focus, and press behavior.',
    defaults: [
      'Default height: 36px',
      'Focus ring + accent shadow on focus-visible',
      'Pressed state: subtle scale + tone shift',
    ],
    usage: [
      {
        id: 'button-whiteboard',
        text: 'Rotation, phase, and setup controls on the whiteboard use shared button variants.',
        href: '/',
        openLabel: 'Open button usage on whiteboard',
      },
      {
        id: 'button-teams',
        text: 'Team creation, import, and management actions reuse the same button system.',
        href: '/teams',
        openLabel: 'Open button usage in teams',
      },
    ],
  },
  {
    id: 'shared-input',
    name: 'Input',
    category: 'Shared UI',
    purpose: 'Single-line text capture with clear focus state and accessible size.',
    defaults: [
      'Default height: 36px',
      'Rounded medium corners',
      'Ring + border change on focus-visible',
    ],
    usage: [
      {
        id: 'input-team-create',
        text: 'Team name and roster editing flows use the shared input behavior.',
        href: '/teams',
        openLabel: 'Open input usage in teams',
      },
      {
        id: 'input-roster',
        text: 'Roster editing and lineup naming rely on the same input styling.',
        href: '/roster',
        openLabel: 'Open input usage in roster',
      },
    ],
  },
  {
    id: 'shared-dropdown',
    name: 'Dropdown Menu',
    category: 'Shared UI',
    purpose: 'Compact action list for mode and selection controls.',
    defaults: [
      'Popover surface + border',
      'Rounded medium menu shell',
      'Hover/focus item highlight using accent surface',
    ],
    usage: [
      {
        id: 'dropdown-rotation',
        text: 'Rotation selection in desktop whiteboard controls uses the dropdown system.',
        href: '/',
        openLabel: 'Open dropdown usage on whiteboard',
      },
      {
        id: 'dropdown-lineup',
        text: 'Lineup selection flows in roster management use dropdown menus.',
        href: '/roster',
        openLabel: 'Open dropdown usage in roster',
      },
    ],
  },
  {
    id: 'shared-context-menu',
    name: 'Context Menu',
    category: 'Shared UI',
    purpose: 'Right-click/press-and-hold contextual actions with grouped options and submenus.',
    defaults: [
      'Compact item rhythm (8-12px vertical hit area)',
      'Clear hover/focus treatment per item',
      'Nested menu support with directional cue',
    ],
    usage: [
      {
        id: 'context-court',
        text: 'Player interactions on the court use context-style action groupings.',
        href: '/',
        openLabel: 'Open player action usage',
      },
      {
        id: 'context-dev',
        text: 'Developer tooling previews use context-menu semantics for grouped controls.',
        href: '/developer/theme-lab',
        openLabel: 'Open developer context example',
      },
    ],
  },
  {
    id: 'shared-overlays',
    name: 'Dialog + Sheet',
    category: 'Shared UI',
    purpose: 'Temporary layers for focused tasks while preserving current screen context.',
    defaults: [
      'Dialog max width and centered layout',
      'Sheet supports edge entry, especially for mobile',
      'Larger roundness than inline controls',
    ],
    usage: [
      {
        id: 'overlay-teams',
        text: 'Team creation and access prompts open in dialog overlays.',
        href: '/teams',
        openLabel: 'Open dialog usage in teams',
      },
      {
        id: 'overlay-gametime',
        text: 'Game setup and onboarding use sheet patterns for narrow screens.',
        href: '/gametime',
        openLabel: 'Open sheet usage in gametime',
      },
    ],
  },
  {
    id: 'shared-tabs',
    name: 'Tabs',
    category: 'Shared UI',
    purpose: 'Switches between related views without route changes.',
    defaults: [
      'Segmented tab list shell',
      'Active tab gets elevated background + border',
      'Clear focus state for keyboard usage',
    ],
    usage: [
      {
        id: 'tabs-roster',
        text: 'Roster management uses tabs for switching assignment contexts.',
        href: '/roster',
        openLabel: 'Open tabs usage in roster',
      },
      {
        id: 'tabs-dev',
        text: 'Developer labs use segmented controls and tab-like interactions for mode switching.',
        href: '/developer/theme-lab',
        openLabel: 'Open tab-like usage in dev labs',
      },
    ],
  },
  {
    id: 'volley-player-token',
    name: 'Player Token',
    category: 'Volleyball',
    purpose: 'Represents each role/player directly on the court with strong identity and fast readability.',
    defaults: [
      'Role color mapping comes from semantic role tokens',
      'Default token size supports touch targeting',
      'Drag/hover/primed states provide clear movement feedback',
    ],
    usage: [
      {
        id: 'token-whiteboard',
        text: 'Tokens are the primary interaction object on the whiteboard court.',
        href: '/',
        openLabel: 'Open token usage on whiteboard',
      },
      {
        id: 'token-settings',
        text: 'Token display preferences are configured in settings.',
        href: '/settings',
        openLabel: 'Open token settings',
      },
    ],
  },
  {
    id: 'volley-player-actions',
    name: 'Player Actions Panel',
    category: 'Volleyball',
    purpose: 'Provides role-specific quick actions and status tags for tactical planning.',
    defaults: [
      'Desktop: anchored popover panel',
      'Mobile: bottom sheet presentation',
      'Status chips support multi-select with clear selected state',
    ],
    usage: [
      {
        id: 'actions-whiteboard',
        text: 'Opening a player on the whiteboard reveals role actions and status toggles.',
        href: '/',
        openLabel: 'Open player actions on whiteboard',
      },
      {
        id: 'actions-mobile',
        text: 'On mobile, the same action model appears in a bottom sheet for reachability.',
        href: '/',
        openLabel: 'Open mobile action behavior',
      },
    ],
  },
]

export const PLAYGROUND_SECTIONS: PlaygroundSection[] = [
  {
    id: 'buttons',
    title: 'Buttons',
    description: 'Compare stock action buttons with your custom variant and tune priority cues.',
    stockComparable: true,
    controls: [
      {
        id: 'accentColor',
        label: 'Accent',
        type: 'color',
        helpText: 'Primary action color in custom lane.',
      },
      {
        id: 'textColor',
        label: 'Text',
        type: 'color',
        helpText: 'Text color on the primary custom button.',
      },
      {
        id: 'radius',
        label: 'Radius',
        type: 'range',
        min: 6,
        max: 20,
        step: 1,
        unit: 'px',
        helpText: 'Corner roundness for custom controls.',
      },
      {
        id: 'height',
        label: 'Height',
        type: 'range',
        min: 36,
        max: 56,
        step: 1,
        unit: 'px',
        helpText: 'Control height to validate touch target comfort.',
      },
      {
        id: 'motionMs',
        label: 'Motion',
        type: 'range',
        min: 80,
        max: 320,
        step: 10,
        unit: 'ms',
        helpText: 'Transition timing used in hover and press previews.',
      },
    ],
    checks: [
      {
        id: 'readability',
        label: 'Readability',
        helpText: 'Checks if text/background contrast is strong enough.',
      },
      {
        id: 'focus',
        label: 'Focus visibility',
        helpText: 'Checks if the focus ring stands out from nearby surfaces.',
      },
      {
        id: 'touch',
        label: 'Touch target',
        helpText: 'Checks if the target reaches at least 44px in height.',
      },
      {
        id: 'states',
        label: 'State distinction',
        helpText: 'Checks if hover/pressed states are visibly different from default.',
      },
    ],
    copyHeading: 'Button style update request',
  },
  {
    id: 'inputs',
    title: 'Inputs',
    description: 'Tune text entry fields for readability, focus clarity, and density.',
    stockComparable: true,
    controls: [
      {
        id: 'surfaceColor',
        label: 'Surface',
        type: 'color',
        helpText: 'Input background color in custom lane.',
      },
      {
        id: 'borderColor',
        label: 'Border',
        type: 'color',
        helpText: 'Default border color in custom lane.',
      },
      {
        id: 'ringColor',
        label: 'Focus ring',
        type: 'color',
        helpText: 'Focus ring color used in custom lane.',
      },
      {
        id: 'radius',
        label: 'Radius',
        type: 'range',
        min: 6,
        max: 18,
        step: 1,
        unit: 'px',
        helpText: 'Corner roundness for fields.',
      },
      {
        id: 'height',
        label: 'Height',
        type: 'range',
        min: 36,
        max: 56,
        step: 1,
        unit: 'px',
        helpText: 'Input height for touch and readability.',
      },
    ],
    checks: [
      {
        id: 'readability',
        label: 'Readability',
        helpText: 'Checks text contrast inside the field.',
      },
      {
        id: 'focus',
        label: 'Focus visibility',
        helpText: 'Checks if focus ring is distinct from border.',
      },
      {
        id: 'touch',
        label: 'Touch target',
        helpText: 'Checks minimum control height.',
      },
    ],
    copyHeading: 'Input style update request',
  },
  {
    id: 'menus',
    title: 'Menus',
    description: 'Compare compact action menu rhythm, hover clarity, and shell styling.',
    stockComparable: true,
    controls: [
      {
        id: 'surfaceColor',
        label: 'Surface',
        type: 'color',
        helpText: 'Menu background in custom lane.',
      },
      {
        id: 'itemHoverColor',
        label: 'Hover',
        type: 'color',
        helpText: 'Hovered row tone in custom lane.',
      },
      {
        id: 'borderColor',
        label: 'Border',
        type: 'color',
        helpText: 'Menu shell border color.',
      },
      {
        id: 'radius',
        label: 'Radius',
        type: 'range',
        min: 6,
        max: 16,
        step: 1,
        unit: 'px',
        helpText: 'Shell corner roundness.',
      },
      {
        id: 'itemHeight',
        label: 'Row height',
        type: 'range',
        min: 30,
        max: 46,
        step: 1,
        unit: 'px',
        helpText: 'Action row hit area.',
      },
    ],
    checks: [
      {
        id: 'readability',
        label: 'Readability',
        helpText: 'Checks row text against menu surface.',
      },
      {
        id: 'touch',
        label: 'Touch target',
        helpText: 'Checks if rows are large enough for touch use.',
      },
      {
        id: 'states',
        label: 'State distinction',
        helpText: 'Checks default vs hover row separation.',
      },
    ],
    copyHeading: 'Menu style update request',
  },
  {
    id: 'overlays',
    title: 'Overlays (Dialog + Sheet)',
    description: 'Tune temporary layers so they feel distinct from regular page surfaces.',
    stockComparable: true,
    controls: [
      {
        id: 'surfaceColor',
        label: 'Surface',
        type: 'color',
        helpText: 'Overlay panel surface in custom lane.',
      },
      {
        id: 'borderColor',
        label: 'Border',
        type: 'color',
        helpText: 'Overlay border color in custom lane.',
      },
      {
        id: 'radius',
        label: 'Radius',
        type: 'range',
        min: 10,
        max: 24,
        step: 1,
        unit: 'px',
        helpText: 'Corner roundness for temporary overlays.',
      },
      {
        id: 'shadow',
        label: 'Shadow depth',
        type: 'range',
        min: 6,
        max: 30,
        step: 1,
        unit: 'px',
        helpText: 'Blur radius for overlay elevation.',
      },
      {
        id: 'motionMs',
        label: 'Motion',
        type: 'range',
        min: 120,
        max: 380,
        step: 10,
        unit: 'ms',
        helpText: 'Entry/exit timing for overlay transitions.',
      },
    ],
    checks: [
      {
        id: 'readability',
        label: 'Readability',
        helpText: 'Checks text contrast on overlay surface.',
      },
      {
        id: 'states',
        label: 'State distinction',
        helpText: 'Checks that overlay surface stands apart from app background.',
      },
    ],
    copyHeading: 'Overlay style update request',
  },
  {
    id: 'tabs',
    title: 'Tabs',
    description: 'Tune segmented navigation clarity between active and inactive states.',
    stockComparable: true,
    controls: [
      {
        id: 'listSurface',
        label: 'List surface',
        type: 'color',
        helpText: 'Background behind all tab triggers.',
      },
      {
        id: 'activeSurface',
        label: 'Active tab',
        type: 'color',
        helpText: 'Background for active tab trigger.',
      },
      {
        id: 'activeText',
        label: 'Active text',
        type: 'color',
        helpText: 'Text color for active tab trigger.',
      },
      {
        id: 'radius',
        label: 'Radius',
        type: 'range',
        min: 8,
        max: 20,
        step: 1,
        unit: 'px',
        helpText: 'Corner roundness for segmented shell and triggers.',
      },
      {
        id: 'height',
        label: 'Trigger height',
        type: 'range',
        min: 34,
        max: 52,
        step: 1,
        unit: 'px',
        helpText: 'Height of each tab trigger.',
      },
    ],
    checks: [
      {
        id: 'readability',
        label: 'Readability',
        helpText: 'Checks active tab text contrast.',
      },
      {
        id: 'states',
        label: 'State distinction',
        helpText: 'Checks active tab is clearly distinct from inactive tabs.',
      },
      {
        id: 'touch',
        label: 'Touch target',
        helpText: 'Checks trigger height against touch guidance.',
      },
    ],
    copyHeading: 'Tabs style update request',
  },
  {
    id: 'player-context',
    title: 'Player Token + Actions',
    description: 'Tune volleyball-specific interaction surfaces across desktop and mobile contexts.',
    stockComparable: false,
    baselineNote: 'No stock shadcn baseline exists for volleyball token and player action patterns. This lane shows your custom system only.',
    controls: [
      {
        id: 'tokenScale',
        label: 'Token scale',
        type: 'range',
        min: 0.8,
        max: 1.4,
        step: 0.05,
        helpText: 'Scales token size for readability and touch confidence.',
      },
      {
        id: 'panelRadius',
        label: 'Panel radius',
        type: 'range',
        min: 8,
        max: 22,
        step: 1,
        unit: 'px',
        helpText: 'Roundness for desktop popover and mobile sheet preview.',
      },
      {
        id: 'panelSurface',
        label: 'Panel surface',
        type: 'color',
        helpText: 'Surface color for player action shell.',
      },
      {
        id: 'motionMs',
        label: 'Motion',
        type: 'range',
        min: 100,
        max: 320,
        step: 10,
        unit: 'ms',
        helpText: 'Transition timing for selection and panel affordances.',
      },
      {
        id: 'presentation',
        label: 'Mobile view',
        type: 'select',
        options: [
          { label: 'Bottom Sheet', value: 'sheet' },
          { label: 'Context Popover', value: 'popover' },
        ],
        helpText: 'Switch between mobile action panel style previews.',
      },
    ],
    checks: [
      {
        id: 'readability',
        label: 'Readability',
        helpText: 'Checks panel text contrast.',
      },
      {
        id: 'touch',
        label: 'Touch target',
        helpText: 'Checks token and action sizes against touch guidance.',
      },
      {
        id: 'states',
        label: 'State distinction',
        helpText: 'Checks selected statuses are clearly distinct from idle states.',
      },
    ],
    copyHeading: 'Player interaction style update request',
  },
]
